language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - george-edison55-precise-backports
    packages:
    - g++-5
    - clang-3.8
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - libcunit1-dev
    - libssl-dev
    - libev-dev
    - libcunit1-dev
    - cmake
    - cmake-data
before_install:
  - $CC --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" EXTRA_LDFLAGS="-fuse-ld=gold"; else export CXX="clang++-3.8" CC="clang-3.8"; fi; fi
  - $CC --version
  - cmake --version
before_script:
  # First build external lib
  - ./ci/build_openssl.sh
  # configure ngtcp2
  - autoreconf -i
  - ./configure --enable-werror PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig CPPFLAGS=-fsanitize=address LDFLAGS="$EXTRA_LDFLAGS -fsanitize=address -Wl,-rpath,$PWD/openssl/build/lib" || cat config.log
script:
  # Now build ngtcp2
  - make check
